#nginx_install_dir : /usr/local/nginx
nginx_install_dir : /opt/app/nginx
nginx_tar_name : nginx-1.15.12.tar.gz
nginx_dir_name : nginx-1.15.12
default_server_listen : 9090

iptables : 
  post : 9090